import Link from "next/link";
import { homeFaq } from "@/components/home/content";
import { ContentImage, FeatureCard, SectionHeading } from "@/components/home/section-primitives";
export function StorySections() {
  return <>
    <section className="home-section story-section" id="story"><div className="page-container story-section__card"><ContentImage className="story-section__image" src="https://images.unsplash.com/photo-1577219491135-ce391730fb2c?auto=format&amp;fit=crop&amp;w=800&amp;q=80" alt="A cook preparing fresh food"/><div className="story-section__copy"><SectionHeading eyebrow="Our journey" title="How PROBOW started"/><p>Born from a couple&apos;s love for food, Probow started with a simple dream &mdash; to make healthy eating exciting.</p><p>We wanted to bring something different to the table: international-inspired healthy dishes with flavours that feel familiar to India.</p><p>At Probow, we believe eating healthy shouldn&apos;t mean eating boring. That&apos;s why we experiment with global flavours, fresh ingredients and our own Indian touch to create meals that are wholesome, flavourful and genuinely enjoyable.</p><p>From refreshing salads to hearty rice bowls, every dish is prepared with the thought of making healthy food something you actually look forward to eating.</p><p>We&apos;re still growing, experimenting and discovering new flavours &mdash; but our goal remains simple: to make healthy food delicious enough that you never feel like you&apos;re compromising.</p></div></div></section>
    <section className="home-section origin-section" id="probow-origin"><div className="page-container origin-section__panel"><div className="origin-section__visual"><div className="origin-section__disc"><ContentImage src="/assets/images/brand-logo/logo-green.png" alt="PROBOW healthy food" className="origin-section__logo"/></div><span className="origin-section__experience">2 years of<br/>caf&eacute; experience</span><span className="origin-section__route"><small>FROM BENGALURU</small><b>To PROBOW</b></span></div><div className="origin-section__copy"><span className="origin-section__kicker">THE IDEA BEHIND PROBOW</span><h2>Healthy food should feel like a <em>food adventure.</em></h2><p>PROBOW comes from a simple belief: eating healthy does not have to mean eating the same food every day.</p><p>Before starting PROBOW, our founder spent two years running a caf&eacute; in Bengaluru. That experience gave us a close look at what people actually enjoy eating, how tastes change, and why customers keep looking for something new.</p><p>We set out to find rare and interesting healthy dishes from around the world and bring them to our city, adding our own spice and flavour along the way.</p><div className="origin-section__callout"><b>From Mediterranean-inspired bowls to international salads and satisfying rice bowls.</b><span>We explore global food ideas, keep the ingredients vegetarian and wholesome, and create our own interpretation for people who love discovering something different in every bite.</span></div><p>For us, PROBOW is more than another healthy food concept. It is our way of experimenting with food &mdash; bringing together international inspiration, familiar Indian flavours and our own special touch.</p><ul className="origin-section__tags"><li>Healthy Bowls</li><li>Rice Bowls</li><li>Mediterranean Bowls</li><li>International Salads</li><li>Indian Fusion</li><li>Food Experiments</li></ul><div className="origin-section__actions"><Link href="/menu">Explore the Menu</Link><a href="#why-probow">Our Food Philosophy <span aria-hidden="true">&#8595;</span></a></div></div></div></section>
  </>;
}

export function HomeFaq() {
  return <section className="home-section faq-section" id="faq"><div className="page-container faq-section__grid"><div><SectionHeading eyebrow="Good to know" title="Frequently asked questions"/><p>Everything you need to know about ordering fresh food from PROBOW in Rajkot.</p><Link className="text-link" href="/contact_us">Have another question? Contact us <span aria-hidden="true">&#8594;</span></Link></div><div className="faq-list">{homeFaq.map(([question,answer]) => <details className="faq-item" key={question}><summary>{question}<span aria-hidden="true">+</span></summary><p>{answer}</p></details>)}</div></div></section>;
}
